In [2]:
df=pd.read_csv("D:\ECH\Dataset\RecomposedESNI4.csv", header=None, names=['target', *(f'C{i:02}' for i in range(284))])
df=df.drop(0, axis=0)

C:\Users\deven\AppData\Local\Temp\ipykernel_37096\2810747793.py:1: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("D:\ECH\Dataset\RecomposedESNI4.csv", header=None, names=['target', *(f'C{i:02}' for i in range(284))])


In [3]:
import pandas as pd
import numpy as np

In [4]:
df

target C00 C01  C02    C03  C04  C05    C06  C07  C08  ...  C274  \
1     AppleMusic   3   1  2.0    0.0  0.0  1.0  252.0  3.0  3.0  ...   0.0   
2     AppleMusic   3   1  2.0   71.0  0.0  2.0   67.0  3.0  3.0  ...   0.0   
3     AppleMusic   3   1  2.0    0.0  0.0  1.0  252.0  3.0  3.0  ...   0.0   
4     AppleMusic   3   1  2.0   71.0  0.0  2.0   67.0  3.0  3.0  ...   0.0   
5     AppleMusic   3   1  2.0   71.0  0.0  2.0   67.0  3.0  3.0  ...   0.0   
...          ...  ..  ..  ...    ...  ...  ...    ...  ...  ...  ...   ...   
3598  YouTube_PC   3   1  0.0  215.0  0.0  0.0  211.0  3.0  3.0  ...   0.0   
3599  YouTube_PC   3   1  0.0  215.0  0.0  0.0  211.0  3.0  3.0  ...   0.0   
3600  YouTube_PC   3   1  0.0  215.0  0.0  0.0  211.0  3.0  3.0  ...   0.0   
3601  YouTube_PC   3   1  2.0    0.0  0.0  1.0  252.0  3.0  3.0  ...   0.0   
3602  YouTube_PC   3   1  2.0    0.0  0.0  1.0  252.0  3.0  3.0  ...   0.0   

      C275  C276  C277  C278  C279  C280  C281  C282  C283  
1      0.0   0.0   0.0   0.0  36.0   0.0  29.0   3.0   4.0  
2      0.0   0.0   2.0   0.0  36.0   0.0  29.0   3.0   4.0  
3      0.0   0.0   0.0   0.0  36.0   0.0  29.0   3.0   4.0  
4      0.0   0.0   2.0   0.0  36.0   0.0  29.0   3.0   4.0  
5      0.0   0.0   2.0   0.0  36.0   0.0  29.0   3.0   4.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3598   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3599   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3600   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3601   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3602   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[3602 rows x 285 columns]

In [5]:
df=df.fillna(0)

In [6]:
#df.replace(r'\t', '', regex=True, inplace=True)
target = df.pop('target')

In [7]:
target

1       AppleMusic
2       AppleMusic
3       AppleMusic
4       AppleMusic
5       AppleMusic
           ...    
3598    YouTube_PC
3599    YouTube_PC
3600    YouTube_PC
3601    YouTube_PC
3602    YouTube_PC
Name: target, Length: 3602, dtype: object

In [8]:
value_counts = target.value_counts()

# Print the result
print(value_counts)

target
ww               1045
Netflix           433
YandexMusic       376
AppleMusic        292
SoundCloud        281
Kinopoisk         268
Spotify           255
YouTube_PC        249
PrimeVideo        191
Live_Facebook     106
Vimeo             106
Name: count, dtype: int64


In [9]:
target

1       AppleMusic
2       AppleMusic
3       AppleMusic
4       AppleMusic
5       AppleMusic
           ...    
3598    YouTube_PC
3599    YouTube_PC
3600    YouTube_PC
3601    YouTube_PC
3602    YouTube_PC
Name: target, Length: 3602, dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target values
y= label_encoder.fit_transform(target)

# Convert the encoded labels to a DataFrame or Series if needed
target = pd.Series(y)


In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Sample DataFrames (replace with your actual data)
# df_modified: DataFrame of features with shape (3547, 18)
# target: Series or DataFrame of target values
X = df
y = target

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

num_replicates = 200

# Initializing lists to store replicated test sets
X_test_replicates = []
y_test_replicates = []

for _ in range(num_replicates):
    X_test_replicates.append(X_test.copy())
    y_test_replicates.append(y_test.copy())

X_test_replicates = np.array(X_test_replicates)
y_test_replicates = np.array(y_test_replicates)

# Save the datasets
# You can save them to a file or keep them in the variables
# For example, if you want to keep them in variables for further processing:


In [12]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder
import csv
import time

def evaluate_model(model, X_test, y_test, label_encoder):
    """Evaluate the model and print the performance metrics."""
    # Predict labels
    y_pred = model.predict(X_test)
    
    # Convert labels back to original class labels
    y_test_classes = label_encoder.inverse_transform(y_test)
    y_pred_classes = label_encoder.inverse_transform(y_pred)
    
    # Compute accuracy
    accuracy = accuracy_score(y_test_classes, y_pred_classes)
    
    # Compute confusion matrix
    conf_matrix = confusion_matrix(y_test_classes, y_pred_classes, labels=label_encoder.classes_)
    
    # Calculate error rates per class
    class_totals = np.sum(conf_matrix, axis=1)
    class_errors = class_totals - np.diag(conf_matrix)
    class_error_rates = class_errors / class_totals
    class_error_rates_percentage = class_error_rates * 100
    
    # Calculate precision and recall
    precision = precision_score(y_test_classes, y_pred_classes, average=None)
    recall = recall_score(y_test_classes, y_pred_classes, average=None)
    
    # Create a DataFrame for class-wise performance
    accuracy_df = pd.DataFrame({
        'Class': label_encoder.classes_,
        'Accuracy (%)': 100 - class_error_rates_percentage,
        'Error Rate (%)': class_error_rates_percentage,
        'Precision (%)': precision * 100,
        'Recall (%)': recall * 100
    })
    
    print("\nClass-wise Performance Table:")
    print(accuracy_df)
    
    # Print overall accuracy
    print(f"\nOverall Accuracy: {accuracy:.4f}")
    
    # Compute and print F1 score
    f1 = f1_score(y_test_classes, y_pred_classes, average='weighted')
    print(f"F1 Score: {f1:.4f}")
    
    # Print confusion matrix
    print("\nConfusion Matrix:")
    print(conf_matrix)

def main():
    # File path to your CSV file
    # data = pd.read_csv('your_file.csv')  # Uncomment and set your CSV file path
    
    # Assuming 'data' is your DataFrame
    # label_encoder = LabelEncoder()
    # data['label'] = label_encoder.fit_transform(data['label'])  # Adjust this line based on your label column
    
    # Split data into features and target
    # X = data.drop('label', axis=1)  # Adjust based on your DataFrame
    # y = data['label']  # Adjust based on your DataFrame

    # Split the data into training and testing sets
    # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize Random Forest Classifier with min_samples_split set to 10
    rf_classifier = RandomForestClassifier(
        n_estimators=150, 
        min_samples_split=10,
        max_features=35,
        random_state=42
    )
    
    # Measure training time
    start_time = time.time()
    
    # Train the model
    rf_classifier.fit(X_train, y_train)
    
    training_time = time.time() - start_time
    print(f"Training Time: {training_time:.4f} seconds")
    # Measure prediction time
    start_time = time.time()
    
    # Evaluate the model
    evaluate_model(rf_classifier, X_test, y_test, label_encoder)
    
    prediction_time = time.time() - start_time
    print(f"Prediction Time: {prediction_time:.4f} seconds")

if __name__ == "__main__":
    main()


Training Time: 1.1261 seconds

Class-wise Performance Table:
            Class  Accuracy (%)  Error Rate (%)  Precision (%)  Recall (%)
0      AppleMusic    100.000000        0.000000     100.000000  100.000000
1       Kinopoisk     98.148148        1.851852     100.000000   98.148148
2   Live_Facebook    100.000000        0.000000     100.000000  100.000000
3         Netflix    100.000000        0.000000     100.000000  100.000000
4      PrimeVideo    100.000000        0.000000     100.000000  100.000000
5      SoundCloud     98.214286        1.785714     100.000000   98.214286
6         Spotify    100.000000        0.000000      98.076923  100.000000
7           Vimeo    100.000000        0.000000     100.000000  100.000000
8     YandexMusic     98.666667        1.333333      98.666667   98.666667
9      YouTube_PC     98.000000        2.000000     100.000000   98.000000
10             ww     99.521531        0.478469      98.578199   99.521531

Overall Accuracy: 0.9931
F1 Score: 0.9

Using Cross Validation

In [13]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import class_weight
from imblearn.over_sampling import SMOTE

# Load your data
# df = pd.read_csv('your_data.csv')  # Uncomment and set your CSV file path
# Assuming df is your features DataFrame and target is your target Series
# target = df['target_column_name']

# Sample data (for illustration)
# Replace this with your actual DataFrame
X = df  # Features DataFrame
y = target  # Target Series

# Calculate class weights
class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(y), y=y)
class_weights_dict = dict(enumerate(class_weights))

# Optional: Using SMOTE to balance the dataset
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

def evaluate_model(model, X_train, y_train, X_test, y_test):
    """Evaluate the model using cross-validation and print the performance metrics."""
    # Perform cross-validation
    cv_scores = cross_val_score(model, X_train, y_train, cv=5)  # 5-fold cross-validation
    
    print(f"\nCross-Validation Scores: {cv_scores}")
    print(f"Mean Cross-Validation Score: {np.mean(cv_scores):.4f}")

    # Train the model on the full training set
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    

    # Print confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("\nConfusion Matrix:")
    print(conf_matrix)

def main():
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

    # Initialize Random Forest Classifier with class weights
    rf_classifier = RandomForestClassifier(
        n_estimators=100,
        max_features=35,  # Adjust this as needed
        random_state=42,
        class_weight=class_weights_dict  # Use class weights
    )

    # Evaluate the model
    print("\nEvaluating model after SMOTE...")
    evaluate_model(rf_classifier, X_train, y_train, X_test, y_test)

if __name__ == "__main__":
    main()



Evaluating model after SMOTE...

Cross-Validation Scores: [0.99619565 0.99673736 0.99836868 0.99836868 0.99945623]
Mean Cross-Validation Score: 0.9978

Confusion Matrix:
[[214   0   0   0   0   0   0   0   0   0   0]
 [  0 217   0   0   0   0   0   0   0   0   0]
 [  0   0 211   0   0   0   0   0   0   0   0]
 [  0   0   0 188   0   0   0   0   0   0   0]
 [  0   0   0   0 199   0   0   0   0   0   1]
 [  0   0   0   0   0 233   0   0   0   0   0]
 [  0   0   0   0   0   0 200   0   0   0   0]
 [  0   0   0   0   0   0   0 235   0   0   0]
 [  0   0   0   0   0   0   0   0 212   0   0]
 [  0   0   0   0   0   0   0   0   0 182   0]
 [  0   0   0   0   0   1   0   0   1   0 205]]


In [14]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import class_weight
from imblearn.over_sampling import SMOTE

# Load your data
# df = pd.read_csv('your_data.csv')  # Uncomment and set your CSV file path
# Assuming df is your features DataFrame and target is your target Series
# target = df['target_column_name']

# Sample data (for illustration)
# Replace this with your actual DataFrame
X = df  # Features DataFrame
y = target  # Target Series

# Calculate class weights
class_weights = class_weight.compute_class_weight('balanced', classes=np.unique(y), y=y)
class_weights_dict = dict(enumerate(class_weights))

# # Optional: Using SMOTE to balance the dataset
# smote = SMOTE(random_state=42)
# X_resampled, y_resampled = smote.fit_resample(X, y)

def evaluate_model(model, X_train, y_train, X_test, y_test):
    """Evaluate the model using cross-validation and print the performance metrics."""
    # Perform cross-validation
    cv_scores = cross_val_score(model, X_train, y_train, cv=5)  # 5-fold cross-validation
    
    print(f"\nCross-Validation Scores: {cv_scores}")
    print(f"Mean Cross-Validation Score: {np.mean(cv_scores):.4f}")

    # Train the model on the full training set
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    

    # Print confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("\nConfusion Matrix:")
    print(conf_matrix)

def main():
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Optional: Using SMOTE to balance the dataset
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_train, y_train)


    # Initialize Random Forest Classifier with class weights
    rf_classifier = RandomForestClassifier(
        n_estimators=100,
        max_features=35,  # Adjust this as needed
        random_state=42,
        class_weight=class_weights_dict  # Use class weights
    )

    # Evaluate the model
    print("\nEvaluating model after SMOTE...")
    evaluate_model(rf_classifier, X_resampled, y_resampled, X_test, y_test)

if __name__ == "__main__":
    main()



Evaluating model after SMOTE...

Cross-Validation Scores: [0.99409237 0.99892531 1.         0.99785062 0.99785062]
Mean Cross-Validation Score: 0.9977

Confusion Matrix:
[[ 61   0   0   0   0   0   0   0   0   0   1]
 [  0  68   0   0   0   0   0   0   0   0   0]
 [  0   0  22   0   0   0   0   0   0   0   0]
 [  0   0   0  88   0   0   0   0   0   0   0]
 [  0   0   0   0  36   0   0   0   0   0   0]
 [  0   0   0   0   0  59   0   0   0   0   0]
 [  0   0   0   0   0   0  42   0   0   0   0]
 [  0   0   0   0   0   0   0  19   0   0   0]
 [  0   0   0   0   0   0   0   0  67   0   2]
 [  0   0   0   0   0   0   0   0   0  57   0]
 [  0   0   0   0   0   0   0   0   0   0 199]]


In [15]:
pip install imblearn


[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [16]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

def evaluate_model(model, X_test, y_test, label_encoder):
    """Evaluate the model and print the performance metrics."""
    # Predict labels
    y_pred = model.predict(X_test)
    
    # Convert labels back to original class labels
    y_test_classes = label_encoder.inverse_transform(y_test)
    y_pred_classes = label_encoder.inverse_transform(y_pred)
    
    # Compute accuracy
    accuracy = accuracy_score(y_test_classes, y_pred_classes)
    
    # Compute confusion matrix
    conf_matrix = confusion_matrix(y_test_classes, y_pred_classes, labels=label_encoder.classes_)
    
    # Calculate error rates per class
    class_totals = np.sum(conf_matrix, axis=1)
    class_errors = class_totals - np.diag(conf_matrix)
    class_error_rates = class_errors / class_totals
    class_error_rates_percentage = class_error_rates * 100
    
    # Create a DataFrame for class-wise performance
    accuracy_df = pd.DataFrame({
        'Class': label_encoder.classes_,
        'Accuracy (%)': 100 - class_error_rates_percentage,
        'Error Rate (%)': class_error_rates_percentage
    })
    
    print("\nClass-wise Performance Table:")
    print(accuracy_df)
    
    # Print overall accuracy
    print(f"\nOverall Accuracy: {accuracy:.4f}")

def main():
    # Load your data (replace with your actual file path)
    # df = pd.read_csv('your_data.csv')
    # target = df['target_column_name']
    
    X = df  # Replace with your features DataFrame
    
    y_encoded=target

    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

    # Define the parameter grid
    param_grid = {
        'n_estimators': [250,300,400,150,100],
        'max_features': [70,35],
        'min_samples_split': [10],
        'class_weight': [None,'balanced']
    }

    # Initialize GridSearchCV
    grid_search = GridSearchCV(
        estimator=RandomForestClassifier(random_state=42),
        param_grid=param_grid,
        cv=5,  # 5-fold cross-validation
        n_jobs=-1,  # Use all available cores
        verbose=2
    )

    # Fit the model using GridSearchCV
    grid_search.fit(X_train, y_train)

    # Best parameters and best estimator
    print(f"\nBest Parameters: {grid_search.best_params_}")
    best_rf_classifier = grid_search.best_estimator_

    # Make predictions
    evaluate_model(best_rf_classifier, X_test, y_test, label_encoder)

if __name__ == "__main__":
    main()

Fitting 5 folds for each of 20 candidates, totalling 100 fits

Best Parameters: {'class_weight': None, 'max_features': 35, 'min_samples_split': 10, 'n_estimators': 400}

Class-wise Performance Table:
            Class  Accuracy (%)  Error Rate (%)
0      AppleMusic    100.000000        0.000000
1       Kinopoisk     98.148148        1.851852
2   Live_Facebook    100.000000        0.000000
3         Netflix    100.000000        0.000000
4      PrimeVideo    100.000000        0.000000
5      SoundCloud     98.214286        1.785714
6         Spotify    100.000000        0.000000
7           Vimeo    100.000000        0.000000
8     YandexMusic     98.666667        1.333333
9      YouTube_PC     98.000000        2.000000
10             ww     99.521531        0.478469

Overall Accuracy: 0.9931
